# Site
title: OS journey
description: This website has the intention to work as a logbook of my long journey into the
  Operating Systems (OS) studies. Here, I describe technical and non-technical
  (rarely) things related to OS. Keep in mind, that I made this logbook for me.
url: https://oslongjourney.github.io
logo: logo.png
locale: en_US
timezone: America/Sao_Paulo
permalink: pretty

# Left Block Images
background:
  homepage: images/home.png                           # this image will be shown on homepage's left block
  post-list: images/home.png             # this image will be shown on post list page
  default-post: images/unsplash-gallery-image-3.jpg   # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /:categories/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: category

# Google Analytics
#google-analytics: UA-XXXXX-Y

# Social Links
email:             siqueira@ime.usp.br
#google.plus:        username
#twitter:            username
#facebook:           username
github:             rodrigosiqueira
linkedin:          rodrigosiqueirajordao
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username

# Gems
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
